name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.26.x
      - uses: golangci/golangci-lint-action@v6
  build:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.26.x
      - run: go build ./cmd/npm-binary-releaser/
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.26.x
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go build ./cmd/npm-binary-releaser/
          ./npm-binary-releaser config
          ./npm-binary-releaser -r ${{steps.semrel.outputs.version}}
        if: steps.semrel.outputs.version != ''
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
